### ISSUE TITLE
with-simulated-input

### ISSUE THREAD

**Issue by akirak** [alphapapa/makem.sh#11]
I found this in one of my starred Emacs Lisp repositories:

https://github.com/DarwinAwardWinner/with-simulated-input

It looks useful in buttercup tests. Have you ever tried it out? I am now thinking of adding it to my test suite.

**Comment by alphapapa** [comment]
Hi Akira,

Yes, actually I corresponded with the author a few years ago, and I've listed it in EPDH here: https://github.com/alphapapa/emacs-package-dev-handbook#testing  I've considered using it to test some of my packages, but IIRC it didn't seem to quite work with Helm like I hoped it would, so I haven't used it yet.  But that's why I added it to the Handbook, so I don't forget about it.  ;)

**Comment by akirak** [comment]
I see, thanks!
