### ISSUE TITLE
Automatically deactivate linters not supporting the current Emacs version

### ISSUE THREAD

**Issue by DamienCassou** [alphapapa/makem.sh#21]
I'm trying to migrate to makem.sh to check my builds. In [this experiment](https://github.com/DamienCassou/ledger-import/pull/1), when trying to build on Emacs 25.3, I get this error message:

```
Checking /tmp/tmp.W8f7lh0e6v/25.3.1/elpa/package-lint-20200221.2122...
Compiling /tmp/tmp.W8f7lh0e6v/25.3.1/elpa/package-lint-20200221.2122/package-lint-autoloads.el...
Compiling /tmp/tmp.W8f7lh0e6v/25.3.1/elpa/package-lint-20200221.2122/package-lint-pkg.el...
Compiling /tmp/tmp.W8f7lh0e6v/25.3.1/elpa/package-lint-20200221.2122/package-lint.el...
Checking /tmp/tmp.W8f7lh0e6v/25.3.1/elpa/package-lint-20200221.2122/data...
Done (Total of 1 file compiled, 2 skipped)
Package ‘emacs-26.1’ is unavailable
ERROR (2020-02-23 11:26:57): Unable to initialize sandbox.
##[error]Process completed with exit code 1.
```

According to [this message](https://github.com/DamienCassou/ledger-import/pull/1#issuecomment-590202161), there is a possibility that one of the linters require Emacs 26.1. The log doesn't say which one so makem's user is left with investigation work. I think makem.sh should automatically take care of deactivating the linters that are not compatible with the selected Emacs version. Alternatively, makem.sh could say which linter breaks the build.

**Comment by DamienCassou** [comment]
relint seems to be the one responsible: https://github.com/mattiase/relint/blob/master/relint.el#L7

**Comment by alphapapa** [comment]
This is a good idea, but I don't think it would be feasible to do so.  

How would makem.sh know which linters require which versions of Emacs?  That would require downloading the package metadata from ELPA, parsing it to get the packages and their minimum Emacs versions, and comparing that to the current version of Emacs, then acting accordingly.  I certainly wouldn't want to do all that in shell, even if it were possible.

> Alternatively, makem.sh could say which linter breaks the build.

That's also a good idea, but I think it would also add significant complexity.  At the least, we'd have to install each package in a separate run of Emacs, which would significantly slow down the installation process.  Or we'd have to write an Elisp wrapper to install packages and give more detailed output when one fails to install.  

But all of that feels out of scope for this package.  This script is already much more complex than I planned.

I think the best we could do here is try to ignore errors from installing linters and then proceed despite missing ones.  But even that presents problems, because what if a temporary network error prevents the installation of ones that should be installable, and then the user proceeds, thinking those linters are unavailable?  He might not notice the missing linters and think that they are installed and passing instead of missing.

As long as this is a matter of supporting Emacsen older than 26.1, I'm willing to forego that support.  I know that some packages want to support older versions, but as far as this script goes, I'm happy to draw the line there and look forward, because I feel like this is complicated enough.

What do you think?

Thanks.

**Comment by DamienCassou** [comment]
An alternative solution would be for makem.sh to maintain its own list of minimal Emacs version for each linter. This way, makem.sh knows which linter to deactivate depending on the Emacs version being used.

Because makem.sh only supports a few linters and because linters probably don't change their minimum Emacs version too often, I don't think maintaining the list will be a burden.

> I'm willing to forego that support

In my packages, I typically try to support the current release (i.e., 26.3) and the latest previous major (i.e, 25.3).

**Comment by alphapapa** [comment]
That is also an option, and you are probably right that the minimum versions wouldn't change often.  However, I'm still reluctant to add the additional complexity to the script (parsing version numbers, comparing their major and minor versions, conditionally enabling linters, etc, which would be rather messy in Bash).  I'm not convinced that it's worth it at this time.

For packages that do need to support older versions of Emacs, it's not much trouble to, e.g. comment out `relint` from the list of linters.  It's intended that packages can make small customizations like that when necessary.  And git should make it easy enough to merge upstream changes to `makem.sh` while preserving those customizations.  I envision that most packages won't need to update `makem.sh` often, anyway.

I hate to not support your packages in this way, but when I start a new project related to Emacs, I generally prefer to start from where Emacs is now and look forward, rather than adding backward-compatibility workarounds.  So I'd prefer that users who need to do this make the necessary customizations themselves.

I should probably add documentation about this to the readme.  Does that seem reasonable?

**Comment by DamienCassou** [comment]
I will workaround the problem in my package. Thank you!

**Comment by DamienCassou** [comment]
I created a new issue to improve documentation: https://github.com/alphapapa/makem.sh/issues/22.

**Comment by alphapapa** [comment]
Ok, thanks for your feedback, Damien.  :)
